# Segredos para conexão com o Supabase
SUPABASE_URL = "https://uptkifwqugtcrhgfyquz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwdGtpZndxdWd0Y3JoZ2Z5cXV6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDI4NDMwOCwiZXhwIjoyMDY1ODYwMzA4fQ.uIbZxzZc9w5fU0j1UUs34EndbMWnMp9AFkX2ENwDWo4"
